OkulOtomasyonu/Models/EntityFramework/Yoneticiler.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulOtomasyonu.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Yoneticiler
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public string k_adi { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [StringLength(50, ErrorMessage = "Şifre en fazla {1}, en az {2} karakter uzunluğunda olmalıdır!", MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string sifre { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [System.Web.Mvc.Compare("sifre", ErrorMessage = "İki şifre eşleşmiyor!")]
        [DataType(DataType.Password)]
        public string sifre2 { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                           @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                           @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
                           ErrorMessage = "Email adresi geçersiz")]
        public string email { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public string gizlisoru { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public string gizlicevap { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [DataType(DataType.Time)]
        public Nullable<System.DateTime> songiristarihi { get; set; }
    }
}

OkulOtomasyonu/Controllers/YoneticilerController.cs
using OkulOtomasyonu.Models.EntityFramework;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace OkulOtomasyonu.Controllers
{
    public class YoneticilerController : Controller
    {
        private SchoolDatabaseEntities2 db = new SchoolDatabaseEntities2();

        // GET: Yoneticiler
        public ActionResult Index(string sort)
        {
            var list = db.Yoneticiler.ToList();
            if (sort == "kadi")
            {
                list = list.OrderBy(x => x.k_adi).ToList();
            }
            else if (sort == "email")
            {
                list = list.OrderBy(x => x.email).ToList();
            }
            else if (sort == "sgt")
            {
                list = list.OrderBy(x => x.songiristarihi).ToList();
            }

            return View(list);
        }
        [HttpPost]
        public ActionResult Index([Bind(Include = "k_adi,email")] Yoneticiler yoneticiler)
        {

            var yoneticiler2 = db.Yoneticiler.ToList();

            if (yoneticiler.k_adi == null && yoneticiler.email == null)
            {
                yoneticiler2 = db.Yoneticiler.ToList();
                return RedirectToAction("Index/");
            }
            else if (yoneticiler.k_adi != null || yoneticiler.email != null)
            {
                var movies = from m in db.Yoneticiler
                             select m;
                yoneticiler2 = movies.Where(m => m.k_adi.Contains(yoneticiler.k_adi) || m.email.Contains(yoneticiler.email)).ToList();


            }
            if (yoneticiler2.Count() == 0)
            {
                TempData["searcherror"] = "Aradığınız bulunamamıştır.";
                return RedirectToAction("Index/", TempData["searcherror"]);
            }

            return View(yoneticiler2);


        }
        // GET: Yoneticiler/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yoneticiler yoneticiler = db.Yoneticiler.Find(id);
            if (yoneticiler == null)
            {
                return HttpNotFound();
            }
            return View(yoneticiler);
        }

        // GET: Yoneticiler/Create
        public ActionResult Create()
        {
            var list = db.Yoneticiler.ToList();
            var list2 = list.Max(x => x.id);
            ViewBag.maxid = list2 + 1;
            return View();
        }

        // POST: Yoneticiler/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,k_adi,sifre,sifre2,email,gizlisoru,gizlicevap,songiristarihi")] Yoneticiler yoneticiler)
        {
            var list = db.Yoneticiler.ToList();
            var list2 = list.Max(x => x.id);
            ViewBag.maxid = list2 + 1;
            if (ModelState.IsValid)
            {

                var yoneticiler2 = db.Yoneticiler.Where(m => m.id != yoneticiler.id && m.k_adi == yoneticiler.k_adi).ToList();
                var yoneticiler3 = db.Yoneticiler.Where(m => m.id != yoneticiler.id && m.email == yoneticiler.email).ToList();
                if (yoneticiler2.Count() != 0 && yoneticiler3.Count() != 0)
                {
                    TempData["Error3"] = "Bu Kullanıcı adında bir yönetici vardır.";
                    TempData["Error4"] = "Bu E-Mail'e sahip bir yönetici vardır.";
                    return RedirectToAction("Create");
                }
                else if (yoneticiler2.Count() != 0)
                {
                    TempData["Error3"] = "Bu Kullanıcı adında bir yönetici vardır.";
                    return RedirectToAction("Create");
                }
                else if (yoneticiler3.Count() != 0)
                {
                    TempData["Error4"] = "Bu E-Mail'e sahip bir yönetici vardır.";
                    return RedirectToAction("Create");
                }

                else
                {
                    db.Yoneticiler.Add(yoneticiler);
                    db.SaveChanges();
                    TempData["create"] = yoneticiler.k_adi + " kullanıcı adlı yönetici eklendi";
                    return RedirectToAction("Index", TempData["create"]);
                }

            }

            return View(yoneticiler);
        }

        // GET: Yoneticiler/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yoneticiler yoneticiler = db.Yoneticiler.Find(id);
            if (yoneticiler == null)
            {
                return HttpNotFound();
            }
            return View(yoneticiler);
        }

        // POST: Yoneticiler/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,k_adi,sifre,sifre2,email,gizlisoru,gizlicevap,songiristarihi")] Yoneticiler yoneticiler)
        {
            if (ModelState.IsValid)
            {
                var yoneticiler2 = db.Yoneticiler.Where(m => m.id != yoneticiler.id && m.k_adi == yoneticiler.k_adi).ToList();
                var yoneticiler3 = db.Yoneticiler.Where(m => m.id != yoneticiler.id && m.email == yoneticiler.email).ToList();
                if (yoneticiler2.Count() != 0 && yoneticiler3.Count() != 0)
                {
                    TempData["Error3"] = "Bu Kullanıcı adında bir yönetici vardır.";
                    TempData["Error4"] = "Bu E-Mail'e sahip bir yönetici vardır.";
                    return RedirectToAction("Edit/" + yoneticiler.id);
                }
                else if (yoneticiler2.Count() != 0)
                {
                    TempData["Error3"] = "Bu Kullanıcı adında bir yönetici vardır.";
                    return RedirectToAction("Edit/" + yoneticiler.id);
                }
                else if (yoneticiler3.Count() != 0)
                {
                    TempData["Error4"] = "Bu E-Mail'e sahip bir yönetici vardır.";
                    return RedirectToAction("Edit/" + yoneticiler.id);
                }

                else
                {
                    db.Entry(yoneticiler).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["create"] = yoneticiler.k_adi + " kullanıcı adlı yönetici güncellendi";
                    return RedirectToAction("Index", TempData["create"]);
                }

            }
            return View(yoneticiler);
        }

        // GET: Yoneticiler/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yoneticiler yoneticiler = db.Yoneticiler.Find(id);
            if (yoneticiler == null)
            {
                return HttpNotFound();
            }
            return View(yoneticiler);
        }

        // POST: Yoneticiler/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Yoneticiler yoneticiler = db.Yoneticiler.Find(id);
            db.Yoneticiler.Remove(yoneticiler);
            db.SaveChanges();
            TempData["create"] = yoneticiler.k_adi + " kullanıcı adlı yönetici silindi";
            return RedirectToAction("Index", TempData["create"]);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OkulOtomasyonu/Views/Yoneticiler/Create.cshtml
@model OkulOtomasyonu.Models.EntityFramework.Yoneticiler

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Yeni Yönetici Ekle</h5>

            </div>

            @using (Html.BeginForm("Create", "Yoneticiler", FormMethod.Post, new { id = "myForm" }))
            {
                <div class="modal-body">

                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <style>
                            .span-danger {
                                font-size: 12px !important;
                                opacity: 0.9;
                                position: fixed;
                            }
                        </style>

                        @Html.ValidationSummary(true, "", new { @class = "text-danger span-danger" })

                        <div class="form-group row">
                            <div class="col-6">
                                <input style="display:none;" readonly class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" data-val="true" data-val-number="The field id must be a number." data-val-required="id alanı gereklidir." id="id" name="id" type="text" value="@ViewBag.maxid">

                            </div>
                        </div>

                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Kullanıcı Adı:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input  onclick="spanAdi()" class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" id="k_adi" name="k_adi" type="text" value="">
                                @Html.ValidationMessageFor(model => model.k_adi, "", new { @class = "text-danger span-danger ", id = "spanadi" })
                                <span id="tc_noNotError2" class="field-validation-valid text-danger span-danger">@TempData["Error3"]</span>
                             </div>
                        </div>
                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Şifre:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input  onclick="spanSoyadi()" class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" id="sifre" name="sifre" type="password" value="">
                                @Html.ValidationMessageFor(model => model.sifre, "", new { @class = "text-danger span-danger", id = "spansoyadi" })
                                
                                      <input class="password-check" type="checkbox" id="input-sifre2" onchange="myChangle()" onclick="myFunction()">
                               
                            </div>
                        </div>
                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Şifre Tekrarı:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input onclick="spanSifreTekrar()" class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" id="sifre2" name="sifre2" type="password" value="">
                                @Html.ValidationMessageFor(model => model.sifre2, "", new { @class = "text-danger span-danger", id = "spansifretekrar" })
                                <input class="password-check" type="checkbox" id="input-sifre2" onchange="myChangle()" onclick="myFunction2()">
                             </div>
                        </div>
                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>E Mail:</b></label><text class="star">*</text>
                            <div class="col-6">

                                <input   onclick="spanTcno()"  class="form-control  mr-sm-2 btn-sm in-margin  single-line" id="email" name="email" type="email" value="">
                                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger span-danger", id = "spantcno" })
                             <span class="field-validation-valid text-danger span-danger"> @TempData["Error4"] </span>
                             </div>
                        </div>

                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Gizli Soru:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input  onclick="spanOno()"  class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" id="gizlisoru"  name="gizlisoru" type="text" value="">
                                @Html.ValidationMessageFor(model => model.gizlisoru, "", new { @class = "text-danger span-danger", id = "spanono" })

                               
                            </div>
                        </div>
                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Gizli Cevap:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input class="input-validation-error form-control  mr-sm-2 btn-sm in-margin datepicker text-box single-line" onclick="spanDtarihi()"  id="gizlicevap" name="gizlicevap" type="text" value="">
                                @Html.ValidationMessageFor(model => model.gizlicevap, "", new { @class = "text-danger span-danger", id = "spandtarihi" })

                            </div>
                        </div>
                        <div style="display:none;" class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Son Giriş Tarihi:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input class="input-validation-error form-control  mr-sm-2 btn-sm in-margin text-box single-line" onclick="spanAdres()"  id="songiristarihi" name="songiristarihi" type="text" value="@DateTime.Today.ToShortDateString()">
                                @Html.ValidationMessageFor(model => model.songiristarihi, "", new { @class = "text-danger span-danger", id = "spanadres" })
                            </div>
                        </div>


                    </div>

                </div>
                <div class="modal-footer">
                    <a href="/Yoneticiler/Index" class="btn btn-outline-dark">Listeye Dön</a>
                    <input onclick="return bootboxCreateAdmin()" type="button" id="Create" value="Kaydet" class="btn btn-outline-success" />

                </div>
            }
        </div>
    </div>
</div>

OkulOtomasyonu/Views/Yoneticiler/Delete.cshtml
@model OkulOtomasyonu.Models.EntityFramework.Yoneticiler

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Yönetici Silinsin mi?</h5>

            </div>

            <div class="modal-body">
                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Kullanıcı Adı:</b></label>
                    <div class="col-6">
                        @Html.DisplayFor(model => model.k_adi)

                    </div>
                </div>

                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Şifre:</b></label>
                    <div class="col-6">
                       @{
                           if (Model.id.ToString() == HttpContext.Current.User.Identity.Name)
                           {
                            @Model.sifre
                           } }
                    </div>
                </div>

                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>E Mail:</b></label>
                    <div class="col-6">
                        @Html.DisplayFor(model => model.email)

                    </div>
                </div>


                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Gizli Soru:</b></label>
                    <div class="col-6">
                       @{
                           if (Model.id.ToString() == HttpContext.Current.User.Identity.Name)
                           {
                            @Model.gizlisoru
                           } }
                    </div>
                </div>

                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Gizli Cevap:</b></label>
                    <div class="col-6">
                       @{
                           if (Model.id.ToString() == HttpContext.Current.User.Identity.Name)
                           {
                            @Model.gizlicevap
                           } }
                    </div>
                </div>

                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Son Giriş Tarihi:</b></label>
                    <div class="col-6">
                        @{
                            var deger = "";
                            if (Model.songiristarihi != null)
                            {
                                deger = Model.songiristarihi.Value.ToShortDateString();
                            } }
                        @deger
                    </div>



                </div>

                <div class="modal-footer">

                    @using (Html.BeginForm("Delete", "Yoneticiler", FormMethod.Post, new { id = "myForm" }))
            {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
<a href="/Yoneticiler/Index" class="btn btn-outline-dark">Listeye Dön</a>
                            <input onclick="return bootboxDeleteAdmin()" type="button" id="Delete" value="Sil" class="btn btn-outline-warning" />

                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
</div>

OkulOtomasyonu/Views/Yoneticiler/Edit.cshtml
@model OkulOtomasyonu.Models.EntityFramework.Yoneticiler

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Yönetici Güncelle</h5>

            </div>

            @using (Html.BeginForm("Edit", "Yoneticiler", FormMethod.Post, new { id = "myForm" }))
            {
                <div class="modal-body">

                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <style>
                            .span-danger {
                                font-size: 12px !important;
                                opacity: 0.9;
                                position: fixed;
                            }
                        </style>

                        @Html.ValidationSummary(true, "", new { @class = "text-danger span-danger" })
                        @Html.HiddenFor(model=>model.id)
                        

                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Kullanıcı Adı:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input onclick="spanAdi()" class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" id="k_adi" name="k_adi" type="text" value="@{var k_adi = Model.k_adi.Trim().Replace("  ", string.Empty);  @k_adi}">
                                @Html.ValidationMessageFor(model => model.k_adi, "", new { @class = "text-danger span-danger ", id = "spanadi" })
                                <span id="tc_noNotError2" class="field-validation-valid text-danger span-danger">@TempData["Error3"]</span>
                            </div>
                        </div>
                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Şifre:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input onclick="spanSoyadi()" class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" id="sifre" name="sifre" type="password" value="@{var sifre = Model.sifre.Trim().Replace(" ", string.Empty);  @sifre}">
                                @Html.ValidationMessageFor(model => model.sifre, "", new { @class = "text-danger span-danger", id = "spansoyadi" })
                              @{
                                  if (Model.id.ToString() == HttpContext.Current.User.Identity.Name)
                                  {
                                      <input class="password-check" type="checkbox" id="input-sifre2" onchange="myChangle()" onclick="myFunction()">
                         
                                    
                                  }
                                  else
                                  {
                                      
                                  }
                            }
                                
                                     </div>
                        </div>
                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Şifre Tekrarı:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input onclick="spanSifreTekrar()" class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" id="sifre2" name="sifre2" type="password" value="@{var sifre2 = Model.sifre.Trim().Replace(" ", string.Empty);  @sifre2}">
                                @Html.ValidationMessageFor(model => model.sifre2, "", new { @class = "text-danger span-danger", id = "spansifretekrar" })
                                @{
                                    if (Model.id.ToString() == HttpContext.Current.User.Identity.Name)
                                    {
                                        <input class="password-check" type="checkbox" id="input-sifre2" onchange="myChangle()" onclick="myFunction2()">


                                    }
                                    else
                                    {

                                    }
                                } </div>
                        </div>
                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>E Mail:</b></label><text class="star">*</text>
                            <div class="col-6">

                                <input onclick="spanTcno()" class="form-control  mr-sm-2 btn-sm in-margin  single-line" id="email" name="email" type="email" value="@{var email = Model.email.Trim().Replace(" ", string.Empty);  @email}">
                                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger span-danger", id = "spantcno" })
                                <span class="field-validation-valid text-danger span-danger"> @TempData["Error4"] </span>
                            </div>
                        </div>

                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Gizli Soru:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input onclick="spanOno()" class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" id="gizlisoru" name="gizlisoru" type="@{
                                    if (Model.id.ToString() == HttpContext.Current.User.Identity.Name)
                                    {
                                        var text = "text";
                                        @text
                                    }
                                    else
                                    {
                                       var text = "password";
                                        @text
                                        }
                                    }" value="@{var gizlisoru = Model.gizlisoru.Trim().Replace("  ", string.Empty);  @gizlisoru}">
                                @Html.ValidationMessageFor(model => model.gizlisoru, "", new { @class = "text-danger span-danger", id = "spanono" })


                            </div>
                        </div>
                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Gizli Cevap:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input class="input-validation-error form-control  mr-sm-2 btn-sm in-margin datepicker text-box single-line" onclick="spanDtarihi()" id="gizlicevap" name="gizlicevap" type="@{
                                    if (Model.id.ToString() == HttpContext.Current.User.Identity.Name)
                                    {
                                        var text = "text";
                                        @text
                                    }
                                    else
                                    {
                                       var text = "password";
                                        @text
                                        }
                                    }" value="@{var gizlicevap = Model.gizlicevap.Trim().Replace("  ", string.Empty);  @gizlicevap}">
                                @Html.ValidationMessageFor(model => model.gizlicevap, "", new { @class = "text-danger span-danger", id = "spandtarihi" })

                            </div>
                        </div>
                        <div style="display:none;" class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Son Giriş Tarihi:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input class="input-validation-error form-control  mr-sm-2 btn-sm in-margin text-box single-line" onclick="spanAdres()" id="songiristarihi" name="songiristarihi" type="text" value="@DateTime.Today.ToShortDateString()">
                                @Html.ValidationMessageFor(model => model.songiristarihi, "", new { @class = "text-danger span-danger", id = "spanadres" })
                            </div>
                        </div>


                    </div>

                </div>
                <div class="modal-footer">
                    <a href="/Yoneticiler/Index" class="btn btn-outline-dark">Listeye Dön</a>
                    <input style="@{
                                    if (Model.id.ToString() == HttpContext.Current.User.Identity.Name)
                                    {
                                        var text = "display:inherit";
                                        @text
                                    }
                                    else
                                    {
                                       var text = "display:none;";
                                        @text
                                        }
                                    }" onclick="return bootboxUpdateAdmin()" type="button" id="Update" value="Kaydet" class="btn btn-outline-success" />

                </div>
            }
        </div>
    </div>
</div>




















               