OkulOtomasyonu/Models/EntityFramework/Ogrenciler.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulOtomasyonu.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Text;

    public partial class Ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenciler()
        {
            this.OgrenciDers = new HashSet<OgrenciDers>();
        }
      
        public int id { get; set; }
        
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public string adi { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public string soyadi { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public string tc_no { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public string o_no { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [DataType(DataType.Time)]
        public System.DateTime d_tarihi { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public string adres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDers> OgrenciDers { get; set; }
        public object Title { get; internal set; }
    }
}

OkulOtomasyonu/Controllers/OgrencilerController.cs
using OkulOtomasyonu.Models.EntityFramework;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace OkulOtomasyonu.Controllers
{

    public class OgrencilerController : Controller
    {
        private SchoolDatabaseEntities2 db = new SchoolDatabaseEntities2();

        // GET: Ogrenciler

        public ActionResult Index(string sort)
        {
            var list = db.Ogrenciler.ToList();
            if (sort == "adi")
            {


                list = list.OrderBy(x => x.adi).ToList();
                TempData["tsort"] = "ida";


            }
            else if (sort == "ida")
            {
                list = list.OrderByDescending(x => x.adi).ToList();
            }
            else if (sort == "soyadi")
            {
                list = list.OrderBy(x => x.soyadi).ToList();
            }
            else if (sort == "tcno")
            {
                list = list.OrderBy(x => x.tc_no).ToList();
            }
            else if (sort == "ono")
            {
                list = list.OrderBy(x => x.o_no).ToList();
            }
            else if (sort == "dtarihi")
            {
                list = list.OrderBy(x => x.d_tarihi).ToList();
            }
            else if (sort == "adres")
            {
                list = list.OrderBy(x => x.adres).ToList();
            }



            return View(list);
        }
        [HttpPost]
        public ActionResult Index([Bind(Include = "adi,soyadi,tc_no,o_no,adres")] Ogrenciler ogrenciler)
        {

            var ogrenciler2 = db.Ogrenciler.ToList();

            if (ogrenciler.adi == null && ogrenciler.soyadi == null && ogrenciler.tc_no == null && ogrenciler.o_no == null)
            {
                ogrenciler2 = db.Ogrenciler.ToList();
                return RedirectToAction("Index/");
            }
            else if (ogrenciler.adi != null || ogrenciler.soyadi != null || ogrenciler.tc_no != null || ogrenciler.o_no != null)
            {
                var movies = from m in db.Ogrenciler
                             select m;
                ogrenciler2 = movies.Where(m => m.adi.Contains(ogrenciler.adi) || m.soyadi.Contains(ogrenciler.soyadi) || m.tc_no.Contains(ogrenciler.tc_no) || m.o_no.Contains(ogrenciler.o_no)).ToList();


            }
            if (ogrenciler2.Count() == 0)
            {
                TempData["searcherror"] = "Aradığınız bulunamamıştır.";
                return RedirectToAction("Index/", TempData["searcherror"]);
            }

            return View(ogrenciler2);


        }

        // GET: Ogrenciler/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ogrenciler ogrenciler = db.Ogrenciler.Find(id);
            if (ogrenciler == null)
            {
                return HttpNotFound();
            }
            return View(ogrenciler);
        }

        // GET: Ogrenciler/Create
        public ActionResult Create()
        {


            var list = db.Ogrenciler.ToList();
            var list2 = list.Max(x => x.id);
            ViewBag.maxid = list2 + 1;

            return View();
        }

        // POST: Ogrenciler/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Create([Bind(Include = "id,adi,soyadi,tc_no,o_no,d_tarihi,adres")] Ogrenciler ogrenciler)
        {
            var list = db.Ogrenciler.ToList();
            var list2 = list.Max(x => x.id);
            ViewBag.maxid = list2 + 1;

            if (ModelState.IsValid)
            {




                var ogrenciler2 = db.Ogrenciler.Where(m => m.id != ogrenciler.id && m.tc_no == ogrenciler.tc_no).ToList();
                var ogrenciler3 = db.Ogrenciler.Where(m => m.id != ogrenciler.id && m.o_no == ogrenciler.o_no).ToList();
                if (ogrenciler2.Count() != 0 && ogrenciler3.Count() != 0)
                {
                    TempData["Error3"] = "Bu TC Numarasında bir öğrenci vardır.";
                    TempData["Error4"] = "Bu Okul Numarasında bir öğrenci vardır.";
                    return RedirectToAction("Create");
                }
                else if (ogrenciler2.Count() != 0)
                {
                    TempData["Error3"] = "Bu TC Numarasında bir öğrenci vardır.";
                    return RedirectToAction("Create");
                }
                else if (ogrenciler3.Count() != 0)
                {
                    TempData["Error4"] = "Bu Okul Numarasında bir öğrenci vardır.";
                    return RedirectToAction("Create");
                }

                else
                {
                    TempData["create"] = ogrenciler.adi + " isimli öğrenci eklendi";
                    db.Ogrenciler.Add(ogrenciler);
                    db.SaveChanges();
                    return RedirectToAction("Index", TempData["create"]);
                }





            }

            return View(ogrenciler);
        }

        // GET: Ogrenciler/Edit/5

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ogrenciler ogrenciler = db.Ogrenciler.Find(id);
            if (ogrenciler == null)
            {
                return HttpNotFound();
            }
            return View(ogrenciler);
        }

        // POST: Ogrenciler/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Edit([Bind(Include = "id,adi,soyadi,tc_no,o_no,d_tarihi,adres")] Ogrenciler ogrenciler)
        {
            if (ModelState.IsValid)
            {
                var ogrenciler2 = db.Ogrenciler.Where(m => m.id != ogrenciler.id && m.tc_no == ogrenciler.tc_no).ToList();
                var ogrenciler3 = db.Ogrenciler.Where(m => m.id != ogrenciler.id && m.o_no == ogrenciler.o_no).ToList();

                if (ogrenciler2.Count() != 0 && ogrenciler3.Count() != 0)
                {
                    TempData["Error3"] = "Bu TC Numarasında bir öğrenci vardır.";
                    TempData["Error4"] = "Bu Okul Numarasında bir öğrenci vardır.";
                    return RedirectToAction("Edit/" + ogrenciler.id);
                }
                else if (ogrenciler2.Count() != 0)
                {
                    TempData["Error3"] = "Bu TC Numarasında bir öğrenci vardır.";
                    return RedirectToAction("Edit/" + ogrenciler.id);
                }
                else if (ogrenciler3.Count() != 0)
                {
                    TempData["Error4"] = "Bu Okul Numarasında bir öğrenci vardır.";
                    return RedirectToAction("Edit/" + ogrenciler.id);
                }
                else
                {
                    TempData["create"] = ogrenciler.adi + " isimli öğrenci güncellendi";
                    db.Entry(ogrenciler).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index", TempData["create"]);
                }

            }
            return View(ogrenciler);
        }

        // GET: Ogrenciler/Delete/5

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ogrenciler ogrenciler = db.Ogrenciler.Find(id);
            if (ogrenciler == null)
            {
                return HttpNotFound();
            }
            return View(ogrenciler);
        }

        // POST: Ogrenciler/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            Ogrenciler ogrenciler = db.Ogrenciler.Find(id);
            db.Ogrenciler.Remove(ogrenciler);
            db.SaveChanges();
            TempData["create"] = ogrenciler.adi + " isimli öğrenci silindi";
            return RedirectToAction("Index", TempData["create"]);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Assignment(int? id)
        {
            ViewBag.id = id;
            var list = db.OgrenciDers.ToList();
            var list2 = list.Max(x => x.id);
            ViewBag.maxid = list2 + 1;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Assignment([Bind(Include = "id,ders_id2,ogrenci_id")] OgrenciDers ogrenciders)
        {


            if (ModelState.IsValid)
            {
                OgrenciDers ogrenciDers;
                var dersid = 1;
                // OgrenciDers ogrenciler = db.OgrenciDers.Where(m => m.ogrenci_id == ogrenciders.ogrenci_id).FirstOrDefault();
                OgrenciDers ogrenciler3 = (from y in db.OgrenciDers where y.ogrenci_id == ogrenciders.ogrenci_id select y).FirstOrDefault();
                var ogrenciler2 = (from y in db.OgrenciDers where y.ogrenci_id == ogrenciders.ogrenci_id select y).ToList();

                if (ogrenciler3 != null)
                {
                    for (var i = 0; i < ogrenciler2.Count(); i++)
                    {
                        OgrenciDers ogrenciler = (from y in db.OgrenciDers where y.ogrenci_id == ogrenciders.ogrenci_id select y).FirstOrDefault();

OkulOtomasyonu/Views/Ogrenciler/Assignment.cshtml
@model OkulOtomasyonu.Models.EntityFramework.OgrenciDers
@using OkulOtomasyonu.Models.EntityFramework

@{
    ViewBag.Title = "Assignment";
    Layout = "~/Views/Shared/_Layout.cshtml";
    SchoolDatabaseEntities2 db = new SchoolDatabaseEntities2();
    var list = db.OgrenciDers.ToList();
    int i = 0;
}

<div class="" tabindex="-1" role="dialog" >
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Ders Atama</h5>

            </div>

@using (Html.BeginForm("Assignment", "Ogrenciler", FormMethod.Post, new { id = "myForm" }))
            {
    @Html.AntiForgeryToken()

            <div class="modal-body" >

                    <div class="form-horizontal" >
                      
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            <div class="col-md-10">
                                <input style="display:none;" readonly class="form-control text-box single-line" data-val="true" data-val-number="The field id must be a number." data-val-required="id alanı gereklidir." id="id" name="id" type="number" value="@ViewBag.maxid">
                              </div>
                        </div>
                        <h4 class="text-center">
                           
                                @{
                                    int aid = Convert.ToInt32(ViewBag.id);
                                    var list4 = db.Ogrenciler.Where(m => m.id == aid).ToList();
                                    @list4[0].adi @list4[0].soyadi

                                }
                           
                        </h4>
                        <div class="form-group row">
                            <label class="control-label col-md-2" for="ders_id">Ders Seçiniz:</label>
                             <div class="col-md-10">


                                 @{

                                     var list3 = db.Dersler.ToList();

                                     foreach (var item in list3)
                                     {
                                         


                                         var ist = db.OgrenciDers.Where(m => m.ders_id == item.id && m.ogrenci_id == aid).ToList();




                                         <input @{if (ist.Count()!=0) { <text>checked</text> } }  id="ders_id2" name="ders_id2" type="checkbox"  value="@item.id" />   @item.ders_adi
                                         <br />


                                             }}



                                @Html.ValidationMessageFor(model => model.ders_id, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2" for="ogrenci_id">Öğrenci ID:</label>
                            <div class="col-md-10">
                                <input readonly class="form-control text-box single-line" data-val="true" data-val-number="The field ogrenci_id must be a number." id="ogrenci_id" name="ogrenci_id" type="number" value="@ViewBag.id">

                                @Html.ValidationMessageFor(model => model.ogrenci_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                       
                    </div>
                

                        <div class="modal-footer">
                            <a href="/Ogrenciler/Index" class="btn btn-outline-dark" >Listeye Dön</a>
                            <input onclick="return bootboxAssignment()" type="button" id="Assignment" value="Kaydet" class="btn btn-outline-success" />
 </div>
            </div>}
        </div>
    </div>
</div>

OkulOtomasyonu/Views/Ogrenciler/AssignmentList.cshtml
@model IEnumerable<OkulOtomasyonu.Models.EntityFramework.OgrenciDers>

@{
    ViewBag.Title = "AssignmentList";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2 class="text-lg-center text-center">Öğrencinin Dersleri</h2>



<p>

</p>
<div class="mt-lg-5 ml-lg-5 pl-lg-1 ">
    <table class="table table-bordered mt-lg-5 ">

        <tbody>
            <tr>
                <th>
                    Ders Adı
                </th>
                <th>
                    Öğrenci Adı
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dersler.ders_adi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ogrenciler.adi) @Html.DisplayFor(modelItem => item.Ogrenciler.soyadi)
                    </td>

                    <td class="p-2"><a href="/Ogrenciler/Assignment/@ViewBag.id" class="btn btn-outline-primary btn-sm fa fa-pencil " id="@item.id"></a></td>


                </tr>
            }
            <tr>
            <td colspan="2" ></td>
        <td class="p-2">
            <a href="/Ogrenciler/Index" class="btn btn-outline-dark">Listeye Dön</a>
        </td></tr>
        </tbody>
    </table>
</div>

OkulOtomasyonu/Views/Ogrenciler/Create.cshtml
@model OkulOtomasyonu.Models.EntityFramework.Ogrenciler
@using OkulOtomasyonu.Controllers
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Yeni Öğrenci Ekle</h5>

            </div>
            
              @using (Html.BeginForm("Create", "Ogrenciler", FormMethod.Post, new { id = "myForm" }))
              {
                <div class="modal-body">

                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <style>
                            .span-danger
                            {

                            font-size:12px !important;
                            opacity:0.9;
                            position:fixed;
                            
                        }
                        </style>
                       
                        @Html.ValidationSummary(true, "", new { @class = "text-danger span-danger" })
                       
                        <div class="form-group row">
                             <div class="col-6">
                                <input style="display:none;"  readonly class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" data-val="true" data-val-number="The field id must be a number." data-val-required="id alanı gereklidir." id="id" name="id" type="text" value="@ViewBag.maxid">
                              
                                </div>
                        </div>
                       
                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Adı:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input onkeypress="return isNumberKey(event)" onclick="spanAdi()" class="form-control  mr-sm-2 btn-sm in-margin text-box single-line"  id="adi" name="adi" type="text" value="">
                                 @Html.ValidationMessageFor(model => model.adi, "", new { @class = "text-danger span-danger ", id = "spanadi" })
                            </div>
                        </div>
                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Soyadı:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input onkeypress="return isNumberKey(event)"  onclick="spanSoyadi()" class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" id="soyadi" name="soyadi" type="text" value="">
                                 @Html.ValidationMessageFor(model => model.soyadi, "", new { @class = "text-danger span-danger", id = "spansoyadi" })
                            </div>
                        </div>
                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>TC No:</b></label><text class="star">*</text>
                            <div class="col-6">
                               
                                <input onkeypress="return isTextKey(event)" onkeyup="tckimlikkontrolu(this)"  onclick="spanTcno()" maxlength="11"  class="form-control  mr-sm-2 btn-sm in-margin  single-line" id="tc_no" name="tc_no" min="0" type="text" value="">
                                    @Html.ValidationMessageFor(model => model.tc_no, "", new { @class = "text-danger span-danger", id = "spantcno" })
                               <span id="tc_noError" class="field-validation-valid text-danger span-danger"></span>
                                <span id="tc_noNotError" class="field-validation-valid text-success span-danger"></span>
                               
                                 <span id="tc_noNotError2" class="field-validation-valid text-danger span-danger">@TempData["Error3"]</span>
</div>
</div>

                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Okul No:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input onkeypress="return isTextKey(event)"  onclick="spanOno()" maxlength="9" class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" id="o_no" min="0"  name="o_no" type="text" value="">
                                @Html.ValidationMessageFor(model => model.o_no, "", new { @class = "text-danger span-danger", id = "spanono" })
                                
                                    <span class="field-validation-valid text-danger span-danger"> @TempData["Error4"] </span>
</div>
                        </div>
                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Doğum Tarihi:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input class="input-validation-error form-control  mr-sm-2 btn-sm in-margin datepicker text-box single-line"  onclick="spanDtarihi()" data-val="false" data-val-date="Lütfen tarih formatında giriniz" data-val-required="Doğum tarihi alanı gereklidir." id="d_tarihi" name="d_tarihi" type="date" value="">
                                 @Html.ValidationMessageFor(model => model.d_tarihi, "", new { @class = "text-danger span-danger", id = "spandtarihi" })

                            </div>
                        </div>
                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Adres:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input class="input-validation-error form-control  mr-sm-2 btn-sm in-margin text-box single-line"  onclick="spanAdres()" data-val="true" data-val-required="Lütfen bir Adres giriniz." id="adres" name="adres" type="text" value="">
                                 @Html.ValidationMessageFor(model => model.adres, "", new { @class = "text-danger span-danger", id = "spanadres" })
                            </div>
                        </div>


                    </div>

                </div>
                <div class="modal-footer">
                     <a href="/Ogrenciler/Index"  class="btn btn-outline-dark ">Listeye Dön</a>
                    <input onclick="return bootboxCreate()" type="button" id="Create" value="Kaydet" class="btn btn-outline-success"/> 

                </div>
              }
        </div>
    </div>
</div>

        

OkulOtomasyonu/Views/Ogrenciler/Delete.cshtml
@model OkulOtomasyonu.Models.EntityFramework.Ogrenciler

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Öğrenci Silinsin mi?</h5>

            </div>

            <div class="modal-body">
                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Adı:</b></label>
                    <div class="col-6">
                        @Html.DisplayFor(model => model.adi)

                    </div>
                </div>

                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Soyadı:</b></label>
                    <div class="col-6">
                        @Html.DisplayFor(model => model.soyadi)

                    </div>
                </div>

                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>TC No:</b></label>
                    <div class="col-6">
                        @Html.DisplayFor(model => model.tc_no)

                    </div>
                </div>


                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Okul No:</b></label>
                    <div class="col-6">
                        @Html.DisplayFor(model => model.o_no)

                    </div>
                </div>

                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Doğum Tarihi:</b></label>
                    <div class="col-6">
                        @Model.d_tarihi.ToShortDateString()

                    </div>
                </div>

                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Adres:</b></label>
                    <div class="col-6">
                        @Html.DisplayFor(model => model.adres)

                    </div>



                </div>

                <div class="modal-footer">

                    @using (Html.BeginForm("Delete", "Ogrenciler", FormMethod.Post, new { id = "myForm" }))
            {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            
                            <a href="/Ogrenciler/Index"  class="btn btn-outline-dark">Listeye Dön</a>
                            <input onclick="return bootboxDelete()" type="button" id="Delete" value="Sil" class="btn btn-outline-warning" />
                        </div>
                    }
                   
                </div>
            </div>
        </div>
    </div>
</div>

   

OkulOtomasyonu/Views/Ogrenciler/Details.cshtml
@model OkulOtomasyonu.Models.EntityFramework.Ogrenciler

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Detaylı Bilgi</h5>

            </div>

            <div class="modal-body">
                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Adı:</b></label>
                    <div class="col-6">
                        @Html.DisplayFor(model => model.adi)

                    </div>
                </div>

                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Soyadı:</b></label>
                    <div class="col-6">
                        @Html.DisplayFor(model => model.soyadi)

                    </div>
                </div>

                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>TC No:</b></label>
                    <div class="col-6">
                        @Html.DisplayFor(model => model.tc_no)

                    </div>
                </div>


                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Okul No:</b></label>
                    <div class="col-6">
                        @Html.DisplayFor(model => model.o_no)

                    </div>
                </div>

                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Doğum Tarihi:</b></label>
                    <div class="col-6">
                        @Model.d_tarihi.ToShortDateString()

                    </div>
                </div>

                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Adres:</b></label>
                    <div class="col-6">
                        @Html.DisplayFor(model => model.adres)

                    </div>


                    
                </div>

                <div class="modal-footer">
                    <a href="/Ogrenciler/Edit/@Model.id" class="btn btn-outline-success" id="@Model.id">Güncelle</a>
                    <a href="/Ogrenciler/Index" class="btn btn-outline-dark">Listeye Dön</a>
                </div>
            </div>
        </div>
    </div>
</div>