OkulOtomasyonu/Models/EntityFramework/Dersler.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulOtomasyonu.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Dersler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dersler()
        {
            this.OgrenciDers = new HashSet<OgrenciDers>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public int ders_no { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public string ders_adi { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        public string ders_hocasi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDers> OgrenciDers { get; set; }
    }
}

OkulOtomasyonu/Controllers/DerslerController.cs
using OkulOtomasyonu.Models.EntityFramework;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace OkulOtomasyonu.Controllers
{
    public class DerslerController : Controller
    {
        private SchoolDatabaseEntities2 db = new SchoolDatabaseEntities2();

        // GET: Dersler
        public ActionResult Index(string sort)
        {
            var list = db.Dersler.ToList();
            if (sort == "dersno")
            {
                list = list.OrderBy(x => x.ders_no).ToList();
            }
            else if (sort == "dersadi")
            {
                list = list.OrderBy(x => x.ders_adi).ToList();
            }
            else if (sort == "dershocasi")
            {
                list = list.OrderBy(x => x.ders_hocasi).ToList();
            }

            return View(list);
        }
        //POST:Dersler
        [HttpPost]
        public ActionResult Index([Bind(Include = "ders_adi,ders_hocasi")] Dersler dersler)
        {

            var dersler2 = db.Dersler.ToList();

            if (dersler.ders_adi == null && dersler.ders_hocasi == null)
            {
                dersler2 = db.Dersler.ToList();
                return RedirectToAction("Index/");
            }
            else if (dersler.ders_adi != null || dersler.ders_hocasi != null)
            {
                var admin = from m in db.Dersler
                            select m;
                dersler2 = admin.Where(m => m.ders_adi.Contains(dersler.ders_adi) || m.ders_hocasi.Contains(dersler.ders_hocasi)).ToList();


            }
            if (dersler2.Count() == 0)
            {
                TempData["searcherror"] = "Aradığınız bulunamamıştır.";
                return RedirectToAction("Index/", TempData["searcherror"]);
            }

            return View(dersler2);


        }

        // GET: Dersler/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dersler dersler = db.Dersler.Find(id);
            if (dersler == null)
            {
                return HttpNotFound();
            }
            return View(dersler);
        }

        // GET: Dersler/Create
        public ActionResult Create()
        {
            var list = db.Dersler.ToList();
            var list2 = list.Max(x => x.id);
            ViewBag.maxid = list2 + 1;
            var list3 = list.Max(x => x.ders_no);
            ViewBag.maxdersno = list3 + 1;
            return View();
        }

        // POST: Dersler/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,ders_no,ders_adi,ders_hocasi")] Dersler dersler)
        {
            var list = db.Dersler.ToList();
            var list2 = list.Max(x => x.id);
            ViewBag.maxid = list2 + 1;
            var list3 = list.Max(x => x.ders_no);
            ViewBag.maxdersno = list3 + 1;
            if (ModelState.IsValid)
            {
                var dersler2 = db.Dersler.Where(m => m.id != dersler.id && m.ders_no == dersler.ders_no).ToList();
                var dersler3 = db.Dersler.Where(m => m.id != dersler.id && m.ders_adi == dersler.ders_adi).ToList();

                if (dersler2.Count() != 0 && dersler3.Count() != 0)
                {
                    TempData["Error3"] = "Bu Ders Numarası başka bir derse aittir.";
                    TempData["Error4"] = "Bu Ders Adı başka bir derse aittir.";
                    return RedirectToAction("Create");
                }
                else if (dersler2.Count() != 0)
                {
                    TempData["Error3"] = "Bu Ders Numarası başka bir derse aittir.";
                    return RedirectToAction("Create");
                }
                else if (dersler3.Count() != 0)
                {
                    TempData["Error4"] = "Bu Ders Adı başka bir derse aittir.";
                    return RedirectToAction("Create");
                }
                else
                {
                    db.Dersler.Add(dersler);
                    db.SaveChanges();
                    TempData["create"] = dersler.ders_adi + " dersi eklendi";
                    return RedirectToAction("Index", TempData["create"]);
                }


            }

            return View(dersler);
        }

        // GET: Dersler/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dersler dersler = db.Dersler.Find(id);
            if (dersler == null)
            {
                return HttpNotFound();
            }
            return View(dersler);
        }

        // POST: Dersler/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,ders_no,ders_adi,ders_hocasi")] Dersler dersler)
        {
            if (ModelState.IsValid)
            {

                var dersler2 = db.Dersler.Where(m => m.id != dersler.id && m.ders_no == dersler.ders_no).ToList();
                var dersler3 = db.Dersler.Where(m => m.id != dersler.id && m.ders_adi == dersler.ders_adi).ToList();

                if (dersler2.Count() != 0 && dersler3.Count() != 0)
                {
                    TempData["Error3"] = "Bu Ders Numarası başka bir derse aittir.";
                    TempData["Error4"] = "Bu Ders Adı başka bir derse aittir.";
                    return RedirectToAction("Edit/" + dersler.id);
                }
                else if (dersler2.Count() != 0)
                {
                    TempData["Error3"] = "Bu Ders Numarası başka bir derse aittir.";
                    return RedirectToAction("Edit/" + dersler.id);
                }
                else if (dersler3.Count() != 0)
                {
                    TempData["Error4"] = "Bu Ders Adı başka bir derse aittir.";
                    return RedirectToAction("Edit/" + dersler.id);
                }


                else
                {
                    db.Entry(dersler).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["create"] = dersler.ders_adi + " dersi güncellendi";
                    return RedirectToAction("Index", TempData["create"]);
                }

            }
            return View(dersler);
        }

        // GET: Dersler/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dersler dersler = db.Dersler.Find(id);
            if (dersler == null)
            {
                return HttpNotFound();
            }
            return View(dersler);
        }

        // POST: Dersler/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Dersler dersler = db.Dersler.Find(id);
            db.Dersler.Remove(dersler);
            db.SaveChanges();
            TempData["create"] = dersler.ders_adi + " dersi silindi";
            return RedirectToAction("Index", TempData["create"]);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult DersList(int? id)
        {
            ViewBag.id = id;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var ogrenciler = db.OgrenciDers.Where(m => m.ders_id == id);
            if (ogrenciler == null)
            {
                return HttpNotFound();
            }
            return View(ogrenciler);

        }
    }
}

OkulOtomasyonu/Views/Dersler/Create.cshtml
@model OkulOtomasyonu.Models.EntityFramework.Dersler

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Yeni Ders Ekle</h5>

            </div>

            @using (Html.BeginForm("Create", "Dersler", FormMethod.Post, new { id = "myForm" }))
            {
                <div class="modal-body">

                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <style>
                            .span-danger {
                                font-size: 12px !important;
                                opacity: 0.9;
                                position: fixed;
                            }
                        </style>

                        @Html.ValidationSummary(true, "", new { @class = "text-danger span-danger" })

                        <div class="form-group row">
                            <div class="col-6">
                                <input style="display:none;" readonly class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" data-val="true" data-val-number="The field id must be a number." data-val-required="id alanı gereklidir." id="id" name="id" type="text" value="@ViewBag.maxid">

                            </div>
                        </div>

                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Ders No:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input onclick="spanAdi()" class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" id="ders_no" min="0" name="ders_no" 
                                       type="number" value="@ViewBag.maxdersno">
                                @Html.ValidationMessageFor(model => model.ders_no, "", new { @class = "text-danger span-danger ", id = "spanadi" })
                                <span  class="field-validation-valid text-danger span-danger">@TempData["Error3"]</span>
                            </div>
                        </div>
                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Ders Adı:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input onclick="spanSoyadi()" class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" id="ders_adi" name="ders_adi" type="text" value="">
                                @Html.ValidationMessageFor(model => model.ders_adi, "", new { @class = "text-danger span-danger", id = "spansoyadi" })
                                <span  class="field-validation-valid text-danger span-danger">@TempData["Error4"]</span>
                              
                            </div>
                        </div>
                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Ders Hocası:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input onclick="spanSifreTekrar()"  class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" id="ders_hocasi" name="ders_hocasi" type="text" value="">
                                @Html.ValidationMessageFor(model => model.ders_hocasi, "", new { @class = "text-danger span-danger", id = "spansifretekrar" })
                               </div>
                        </div>
                        


                    </div>

                </div>
                <div class="modal-footer">
                    <a href="/Dersler/Index" class="btn btn-outline-dark">Listeye Dön</a>
                    <input onclick="return bootboxCreateLesson()" type="button" id="Create" value="Kaydet" class="btn btn-outline-success" />

                </div>
            }
        </div>
    </div>
</div>

OkulOtomasyonu/Views/Dersler/Delete.cshtml
@model OkulOtomasyonu.Models.EntityFramework.Dersler

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Ders Silinsin mi?</h5>

            </div>

            <div class="modal-body">
                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Ders No:</b></label>
                    <div class="col-6">
                        @Html.DisplayFor(model => model.ders_no)

                    </div>
                </div>

                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Ders Adı:</b></label>
                    <div class="col-6">
                        @Html.DisplayFor(model => model.ders_adi)

                    </div>
                </div>

                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Ders Hocası:</b></label>
                    <div class="col-6">
                        @Html.DisplayFor(model => model.ders_hocasi)

                    </div>
                </div>




                </div>

                <div class="modal-footer">

                    @using (Html.BeginForm("Delete", "Dersler", FormMethod.Post, new { id = "myForm" }))
            {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                             <a href="/Dersler/Index"  class="btn btn-outline-dark">Listeye Dön</a>
                            <input onclick="return bootboxDeleteLesson()" type="button" id="Delete" value="Sil" class="btn btn-outline-warning" />

                         </div>
                    }

                </div>
            </div>
        </div>
    </div>
</div>

OkulOtomasyonu/Views/Dersler/DersList.cshtml
@model IEnumerable<OkulOtomasyonu.Models.EntityFramework.OgrenciDers>

@{
    ViewBag.Title = "DersList";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var list = Model.ToList();
}






<div class="" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Dersin Öğrencileri</h5>

            </div>

            <div class="modal-body">

               



               
                    <table class="table table-bordered  ">

                        <tbody>
                            <tr>
                                <th>
                                    Ders Adı
                                </th>
                                <th>
                                    Öğrenci Adı Soyadı
                                </th>

                            </tr>
                            <tr>
                                @{
                                    if (list.Count() == 0)
                                    {
                                        <th colspan="2">Bu Dersi alan öğrenci yoktur.</th>
                                    }
                                }
                            </tr>



                            @foreach (var item in Model)
                            {

                                <tr>
                                    <td>

                                        @Html.DisplayFor(modelItem => item.Dersler.ders_adi)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Ogrenciler.adi)
                                        @Html.DisplayFor(modelItem => item.Ogrenciler.soyadi)
                                    </td>

                                </tr>
                            }

                            
                        </tbody>
                    </table>
                </div>
            <div class="modal-footer">
                <a href="/Dersler/Index" class="btn btn-outline-dark">Listeye Dön</a>
                </div>
            </div>
    </div>
</div>

OkulOtomasyonu/Views/Dersler/Details.cshtml
@model OkulOtomasyonu.Models.EntityFramework.Dersler

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Detaylı Bilgi</h5>

            </div>

            <div class="modal-body">
                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Ders No:</b></label>
                    <div class="col-6">
                        @Html.DisplayFor(model => model.ders_no)

                    </div>
                </div>

                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Ders Adı:</b></label>
                    <div class="col-6">
                        @Html.DisplayFor(model => model.ders_adi)

                    </div>
                </div>

                <div class="form-group row">
                    <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Ders Hocası:</b></label>
                    <div class="col-6">
                        @Html.DisplayFor(model => model.ders_hocasi)

                    </div>
                </div>





               

                <div class="modal-footer">
                   
                    <a href="/Dersler/Index" class="btn btn-outline-dark">Listeye Dön</a>
                    <a href="/Dersler/Edit/@Model.id" class="btn btn-outline-success" id="@Model.id">Güncelle</a>
                </div>
            </div>
        </div>
    </div>
</div>

OkulOtomasyonu/Views/Dersler/Edit.cshtml
@model OkulOtomasyonu.Models.EntityFramework.Dersler

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Ders Güncelle</h5>

            </div>

            @using (Html.BeginForm("Edit", "Dersler", FormMethod.Post, new { id = "myForm" }))
            {
                <div class="modal-body">

                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <style>
                            .span-danger {
                                font-size: 12px !important;
                                opacity: 0.9;
                                position: fixed;
                            }
                        </style>

                        @Html.ValidationSummary(true, "", new { @class = "text-danger span-danger" })
                        @Html.HiddenFor(model=>model.id)
                        

                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Ders No:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input onclick="spanAdi()" class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" id="ders_no" min="0" name="ders_no"
                                        type="number" value="@Model.ders_no">
                                @Html.ValidationMessageFor(model => model.ders_no, "", new { @class = "text-danger span-danger ", id = "spanadi" })
                                <span class="field-validation-valid text-danger span-danger">@TempData["Error3"]</span>
                            </div>
                        </div>
                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Ders Adı:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input onclick="spanSoyadi()" class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" id="ders_adi" name="ders_adi" 
                                       type="text" value="@{if (Model.ders_adi != null) { var ders_adi = Model.ders_adi.Trim().Replace("  ", string.Empty);  @ders_adi}}">
                                @Html.ValidationMessageFor(model => model.ders_adi, "", new { @class = "text-danger span-danger", id = "spansoyadi" })
                                <span class="field-validation-valid text-danger span-danger">@TempData["Error4"]</span>

                            </div>
                        </div>
                        <div class="form-group row pt-lg-2">
                            <label for="input1" class="col-3 col-form-label text-sm-right mr-sm-2 btn-sm in-margin"><b>Ders Hocası:</b></label><text class="star">*</text>
                            <div class="col-6">
                                <input onclick="spanSifreTekrar()" class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" id="ders_hocasi" name="ders_hocasi" type="text" value="@{if (Model.ders_hocasi != null) { var ders_hocasi = Model.ders_hocasi.Trim().Replace("  ", string.Empty);  @ders_hocasi}}">
                                @Html.ValidationMessageFor(model => model.ders_hocasi, "", new { @class = "text-danger span-danger", id = "spansifretekrar" })
                            </div>
                        </div>



                    </div>

                </div>
                <div class="modal-footer">
                    <a href="/Dersler/Index" class="btn btn-outline-dark">Listeye Dön</a>
                    <input onclick="return bootboxUpdateLesson()" type="button" id="Update" value="Kaydet" class="btn btn-outline-success" />

                </div>
            }
        </div>
    </div>
</div>
    </div>
</div>

OkulOtomasyonu/Views/Dersler/Index.cshtml
@model IEnumerable<OkulOtomasyonu.Models.EntityFramework.Dersler>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int i = 0;
}
<h2 class="text-lg-center text-center">Dersler</h2>



<p>

</p>
<div class="mt-lg-5 ml-lg-5 pl-lg-1 ">
    <table class="table table-bordered mt-lg-5 ">

        <tbody>
            <form action="" id="myForm" method="post">
                <tr class="">


                    <td>
                        <button class="btn-sm btn btn-outline-info fa fa-search" id="search" name="search" type="submit" value=""></button>
                    </td>
                    <td class="p-2">
                         </td>
                    <td class="p-2"><input class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" id="ders_adi" name="ders_adi" type="text" value="">
</td>
                    <td class="p-2">
                        <input class="form-control  mr-sm-2 btn-sm in-margin text-box single-line" id="ders_hocasi" name="ders_hocasi" type="text" value="">
                    </td>
                   

                    <td colspan="4">
                        <span class="text-danger p-2">@TempData["searcherror"]</span>

                    </td>
                </tr>
            </form>
            <tr class="">
                <th class="p-2">Sıra No</th>

                <th class="p-2">Ders No <a href="/Dersler/Index/?sort=dersno" id="sortdersno" class=" btn-outline-dark fa fa-sort-down"></a></th>
                <th class="p-2">Ders Adı <a href="/Dersler/Index/?sort=dersadi" id="sortdersadi" class=" btn-outline-dark fa fa-sort-down"></a></th>
                <th class="p-2">Ders Hocası <a href="/Dersler/Index/?sort=dershocasi" id="sortdershocasi" class=" btn-outline-dark fa fa-sort-down"></a></th>
                
                <td colspan="4" class="text-success p-2">@TempData["create"]</td>

            </tr>
            
            @foreach (var item in Model)
            {
                i++;
                <tr>
                    <td>@i</td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ders_no)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ders_adi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ders_hocasi)
                    </td>
                   

                    <td class="p-2"><a href="/Dersler/Edit/@item.id" class="btn btn-outline-primary btn-sm fa fa-pencil " id="@item.id"></a></td>
                    <td class="p-2"><a href="/Dersler/Details/@item.id" class="btn btn-outline-info btn-sm fa fa-info-circle " id="@item.id"></a></td>
                    <td class="p-2"><a href="/Dersler/Delete/@item.id" id="@item.id" class="btn btn-outline-warning btn-sm fa fa-trash"></a></td>
                    <td class="p-2"><a href="/Dersler/DersList/@item.id" id="@item.id" class="btn btn-outline-dark btn-sm fa fa-list"></a></td>



                </tr>
            }
            <tr><td colspan="4"></td><td colspan="4"><a href="/Dersler/Create" class="btn btn-success btn-sm" name="ekle">Yeni Ders Ekle<i class="ml-lg-1 fa fa-plus-circle"></i></a></td></tr>

        </tbody>
    </table>
</div>